import luigi
import time

class Task1(luigi.Task):
    task_namespace = 'my_tasks'

    def run(self):
        print("Task1: run")
        with self.output().open("w") as target:
            target.write(f"This file was generated by Task1 at {time.asctime()}.\n")

    def output(self):
        print("Task1: output")
        return luigi.LocalTarget("mid/task1.txt")


class Task2(luigi.Task):
    task_namespace = 'my_tasks'

    def requires(self):
        print("Task2: requires")
        return Task1()

    def run(self):
        print("Task2: run")
        with self.input().open("r") as mid, self.output().open("w") as target:
            task1_text = mid.read()

            target.write(task1_text)
            target.write(f"This file was changed by Task2 at {time.asctime()}.\n")

    def output(self):
        print("Task2: output")
        return luigi.LocalTarget("output/task2.txt")


if __name__ == "__main__":
    luigi.run([
        'my_tasks.Task2',
        '--local-scheduler'
    ])
