import luigi
import time

class Task1(luigi.Task):
    task_namespace = 'tasks'

    def run(self):
        print("Task1: run")
        with self.output().open("w") as target:
            target.write(f"This file was generated by Task1 at {time.asctime()}.")

    def output(self):
        print("Task1: output")
        return luigi.LocalTarget("mid/task1.txt")

if __name__ == "__main__":
    luigi.run(['tasks.Task1', '--local-scheduler'])
